default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: by_place_development
  #username: byplace
  #password: <%= Rails.application.credentials.database_password! %>
  #host: soligorsk.place
  #port: 55432
  #sslmode: require
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: by_place_test


production:
  <<: *default
  database: by_place
  username: byplace
  password: <%= Rails.application.credentials.database_password! %>
  host: 127.0.0.1
  #port: 55432